AgileDevelopment/Models/Methodology.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AgileDevelopment.Models
{
    public class Methodology
    {
        public int MethodologyID { get; set; }
        public string Title { get; set; }
        public string? Description { get; set; }

        public ICollection<Member>? Members { get; set; }
        public ICollection<Principle>? Principles { get; set; }
        public ICollection<MethodFramework>? MethodFrameworks { get; set; }
        public ICollection<Practice>? Practices { get; set; }
        public ICollection<Test>? Tests { get; set; }
        public ICollection<WiseSaying>? WiseSayings { get; set; }
    }
}

AgileDevelopment/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgileDevelopment.Data;
using AgileDevelopment.Models;
using AgileDevelopment.Services;

namespace AgileDevelopment.Controllers
{
    public class MembersController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly IMemberService _memberService;

        public MembersController(ApplicationContext context, IMemberService memberService)
        {
            _context = context;
            _memberService = memberService;
        }

        // GET: Members
        public async Task<IActionResult> Index()
        {
              return _context.Member != null ? 
                          View(await _context.Member.ToListAsync()) :
                          Problem("Entity set 'ApplicationContext.Member'  is null.");
        }

        public async Task<IActionResult> ListMembers(int id)
        {
            var members = await _context.Member.ToListAsync();

            return _context.Member != null ?
                        //View("Index", await _context.Member.Where(m => m.MethodologyID == id).ToListAsync()) :
                        View("Index", _memberService.FilterMemberById(id, members)):
                        Problem("Entity set 'ApplicationContext.Member'  is null.");
        }

        // GET: Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Member == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .FirstOrDefaultAsync(m => m.MemberID == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            ViewData["MethodologyId"] = new SelectList(_context.Methodology.ToList(),"MethodologyID", "Title");
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberID,Title,Description,MethodologyID")] Member member)
        {
            if (ModelState.IsValid)
            {
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Member == null)
            {
                return NotFound();
            }

            var member = await _context.Member.FindAsync(id);
            ViewData["MethodologyId"] = new SelectList(_context.Methodology.ToList(),"MethodologyID", "Title");
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberID,Title,Description,MethodologyID")] Member member)
        {
            if (id != member.MemberID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.MemberID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Member == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .FirstOrDefaultAsync(m => m.MemberID == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Member == null)
            {
                return Problem("Entity set 'ApplicationContext.Member'  is null.");
            }
            var member = await _context.Member.FindAsync(id);
            if (member != null)
            {
                _context.Member.Remove(member);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(int id)
        {
          return (_context.Member?.Any(e => e.MemberID == id)).GetValueOrDefault();
        }
    }
}

AgileDevelopment/Controllers/PracticesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgileDevelopment.Data;
using AgileDevelopment.Models;

namespace AgileDevelopment.Controllers
{
    public class PracticesController : Controller
    {
        private readonly ApplicationContext _context;

        public PracticesController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Practices
        public async Task<IActionResult> Index()
        {
              return _context.Practice != null ? 
                          View(await _context.Practice.ToListAsync()) :
                          Problem("Entity set 'ApplicationContext.Practice'  is null.");
        }
        public async Task<IActionResult> ListPractices(int id)
        {
            return _context.Practice != null ?
                        View("Index", await _context.Practice.Where(p => p.MethodologyID == id).ToListAsync()) :
                        Problem("Entity set 'ApplicationContext.Practice'  is null.");
        }
        // GET: Practices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Practice == null)
            {
                return NotFound();
            }

            var practice = await _context.Practice
                .FirstOrDefaultAsync(m => m.PracticeID == id);
            if (practice == null)
            {
                return NotFound();
            }

            return View(practice);
        }

        // GET: Practices/Create
        public IActionResult Create()
        {
            ViewData["MethodologyId"] = new SelectList(_context.Methodology.ToList(),"MethodologyID", "Title");
            return View();
        }

        // POST: Practices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PracticeID,Title,Description,MethodologyID")] Practice practice)
        {
            if (ModelState.IsValid)
            {
                _context.Add(practice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(practice);
        }

        // GET: Practices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Practice == null)
            {
                return NotFound();
            }

            var practice = await _context.Practice.FindAsync(id);
            ViewData["MethodologyId"] = new SelectList(_context.Methodology.ToList(),"MethodologyID", "Title");
            if (practice == null)
            {
                return NotFound();
            }
            return View(practice);
        }

        // POST: Practices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PracticeID,Title,Description,MethodologyID")] Practice practice)
        {
            if (id != practice.PracticeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(practice);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PracticeExists(practice.PracticeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(practice);
        }

        // GET: Practices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Practice == null)
            {
                return NotFound();
            }

            var practice = await _context.Practice
                .FirstOrDefaultAsync(m => m.PracticeID == id);
            if (practice == null)
            {
                return NotFound();
            }

            return View(practice);
        }

        // POST: Practices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Practice == null)
            {
                return Problem("Entity set 'ApplicationContext.Practice'  is null.");
            }
            var practice = await _context.Practice.FindAsync(id);
            if (practice != null)
            {
                _context.Practice.Remove(practice);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PracticeExists(int id)
        {
          return (_context.Practice?.Any(e => e.PracticeID == id)).GetValueOrDefault();
        }
    }
}

AgileDevelopment/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgileDevelopment.Data;
using AgileDevelopment.Models;

namespace AgileDevelopment.Controllers
{
    public class TestsController : Controller
    {
        private readonly ApplicationContext _context;

        public TestsController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Tests
        public async Task<IActionResult> Index()
        {
              return _context.Test != null ? 
                          View(await _context.Test.ToListAsync()) :
                          Problem("Entity set 'ApplicationContext.Test'  is null.");
        }
        public async Task<IActionResult> ListTests(int id)
        {
            return _context.Test != null ?
                        View("Index", await _context.Test.Where(t => t.MethodologyID == id).ToListAsync()) :
                        Problem("Entity set 'ApplicationContext.Test'  is null.");
        }
        // GET: Tests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Test == null)
            {
                return NotFound();
            }

            var test = await _context.Test
                .FirstOrDefaultAsync(m => m.TestID == id);
            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }

        // GET: Tests/Create
        public IActionResult Create()
        {
            ViewData["MethodologyId"] = new SelectList(_context.Methodology.ToList(),"MethodologyID", "Title");
            return View();
        }

        // POST: Tests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TestID,Title,Description,MethodologyID")] Test test)
        {
            if (ModelState.IsValid)
            {
                _context.Add(test);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(test);
        }

        // GET: Tests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Test == null)
            {
                return NotFound();
            }

            var test = await _context.Test.FindAsync(id);
            if (test == null)
            {
                return NotFound();
            }
            return View(test);
        }

        // POST: Tests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TestID,Title,Description")] Test test)
        {
            if (id != test.TestID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(test);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestExists(test.TestID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(test);
        }

        // GET: Tests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Test == null)
            {
                return NotFound();
            }

            var test = await _context.Test
                .FirstOrDefaultAsync(m => m.TestID == id);
            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }

        // POST: Tests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Test == null)
            {
                return Problem("Entity set 'ApplicationContext.Test'  is null.");
            }
            var test = await _context.Test.FindAsync(id);
            if (test != null)
            {
                _context.Test.Remove(test);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestExists(int id)
        {
          return (_context.Test?.Any(e => e.TestID == id)).GetValueOrDefault();
        }
    }
}

AgileDevelopment/Views/Methodologies/Create.cshtml
@model AgileDevelopment.Models.Methodology

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Methodology</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AgileDevelopment/Views/Methodologies/Delete.cshtml
@model AgileDevelopment.Models.Methodology

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Methodology</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MethodologyID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AgileDevelopment/Views/Methodologies/Details.cshtml
@model AgileDevelopment.Models.Methodology

@{
	ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
	<h4>Methodology</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Title)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Title)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Description)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Description)
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model?.MethodologyID">Edit</a> |
	<a asp-action="Index">Back to List</a>
</div>
<div>
	<a asp-controller="Members" asp-action="ListMembers" asp-route-id="@Model?.MethodologyID"><button class="btn btn-primary">
		@Html.DisplayFor(model => model.Title) Members</button>
	</a>


	<a asp-controller="Principles" asp-action="ListPrinciples" asp-route-id="@Model?.MethodologyID"><button class="btn btn-primary" >
		@Html.DisplayFor(model => model.Title) Principles</button>
	</a>


	<a asp-controller="Tests" asp-action="ListTests" asp-route-id="@Model?.MethodologyID"><button class="btn btn-primary">
		@Html.DisplayFor(model => model.Title) Tests</button>
	</a>


	<a asp-controller="Practices" asp-action="ListPractices" asp-route-id="@Model?.MethodologyID"><button class="btn btn-primary">
		@Html.DisplayFor(model => model.Title) Practices</button>
	</a>


	<a asp-controller="MethodFrameworks" asp-action="ListMethodFrameworks" asp-route-id="@Model?.MethodologyID"><button class="btn btn-primary">
		@Html.DisplayFor(model => model.Title) Method Frameworks</button>
	</a>
	<a asp-controller="Wisesayings" asp-action="ListWiseSayings" asp-route-id="@Model?.MethodologyID"><button class="btn btn-primary">
		@Html.DisplayFor(model => model.Title) Wise Sayings</button>
	</a>
</div>

AgileDevelopment/Views/Methodologies/Edit.cshtml
@model AgileDevelopment.Models.Methodology

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Methodology</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MethodologyID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AgileDevelopment/Views/Methodologies/Index.cshtml
@model IEnumerable<AgileDevelopment.Models.Methodology>

@{
    ViewData["Title"] = "Software Development Methodologies";
}

<h1>@ViewBag.Title</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.MethodologyID"><strong>@Html.DisplayFor(modelItem => item.Title)</strong></a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MethodologyID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MethodologyID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MethodologyID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>